name: Publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build and Publish APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Create release keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d \
            --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" \
            --batch \
            release.keystore.asc > release.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleFreeDynamic

      - name: Publish GitHub release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          prerelease: true
          name: "Pre-release"
          files: lemuroid-app/build/outputs/apk/freeDynamic/release/lemuroid-app-free-dynamic-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
